development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  username: AMidili
  password: the4kings
  host: localhost
  port: 5432
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  pool: 5
  username: AMidili
  password: the4kings
  host: localhost
  port: 5432
  timeout: 5000
