development:
  adapter: postgresql
  encoding: unicode
  database: EasyKeep_development
  pool: 5
  username: AMidili
  password: secret
  host: localhost
  port: 5432
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: EasyKeep_test
  pool: 5
  username: AMidili
  password: secret
  host: localhost
  port: 5432
  timeout: 5000
